### 1. Get all tickets
GET https://localhost:7002/api/tickets
Accept: application/json


### 2. Create valid ticket
POST https://localhost:7002/api/tickets
Content-Type: application/json
Accept: application/json

{
  "title": "SQLite test",
  "description": "Should persist"
}


### 3. Get ticket by id
GET https://localhost:7002/api/tickets/1
Accept: application/json


### 4. Get non-existing ticket (404)
GET https://localhost:7002/api/tickets/999
Accept: application/problem+json


### 5. Create invalid ticket (400)
POST https://localhost:7002/api/tickets
Content-Type: application/json
Accept: application/problem+json

{
  "title": "",
  "description": ""
}


### 6. Update ticket
PUT https://localhost:7002/api/tickets/8
Content-Type: application/json
Accept: application/json

{
  "title": "UPDATED CHECK",
  "description": "UPDATED CHECK"
}


### 7. Update ticket status
PUT https://localhost:7002/api/tickets/8/status
Content-Type: application/json
Accept: application/json

{
  "status": "Closed"
}

